// source: ondewo/survey/fhir.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = function () {
	return this || window || global || self || Function('return this')();
}.call(null);

var google_api_annotations_pb = require('../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var ondewo_survey_survey_pb = require('../../ondewo/survey/survey_pb.js');
goog.object.extend(proto, ondewo_survey_survey_pb);
var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js');
goog.object.extend(proto, google_protobuf_struct_pb);
goog.exportSymbol('proto.ondewo.survey.CreateFHIRSurveyRequest', null, global);
goog.exportSymbol('proto.ondewo.survey.SurveyFHIRAnswersResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ondewo.survey.CreateFHIRSurveyRequest = function (opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ondewo.survey.CreateFHIRSurveyRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	/**
	 * @public
	 * @override
	 */
	proto.ondewo.survey.CreateFHIRSurveyRequest.displayName = 'proto.ondewo.survey.CreateFHIRSurveyRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ondewo.survey.SurveyFHIRAnswersResponse = function (opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, proto.ondewo.survey.SurveyFHIRAnswersResponse.repeatedFields_, null);
};
goog.inherits(proto.ondewo.survey.SurveyFHIRAnswersResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	/**
	 * @public
	 * @override
	 */
	proto.ondewo.survey.SurveyFHIRAnswersResponse.displayName = 'proto.ondewo.survey.SurveyFHIRAnswersResponse';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
	 * Creates an object representation of this proto.
	 * Field names that are reserved in JavaScript and will be renamed to pb_name.
	 * Optional fields that are not set will be set to undefined.
	 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
	 * For the list of reserved names please see:
	 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
	 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
	 *     JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @return {!Object}
	 */
	proto.ondewo.survey.CreateFHIRSurveyRequest.prototype.toObject = function (opt_includeInstance) {
		return proto.ondewo.survey.CreateFHIRSurveyRequest.toObject(opt_includeInstance, this);
	};

	/**
	 * Static version of the {@see toObject} method.
	 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
	 *     the JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @param {!proto.ondewo.survey.CreateFHIRSurveyRequest} msg The msg instance to transform.
	 * @return {!Object}
	 * @suppress {unusedLocalVariables} f is only used for nested messages
	 */
	proto.ondewo.survey.CreateFHIRSurveyRequest.toObject = function (includeInstance, msg) {
		var f,
			obj = {
				fhirQuestionnaire:
					(f = msg.getFhirQuestionnaire()) && google_protobuf_struct_pb.Struct.toObject(includeInstance, f)
			};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ondewo.survey.CreateFHIRSurveyRequest}
 */
proto.ondewo.survey.CreateFHIRSurveyRequest.deserializeBinary = function (bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.ondewo.survey.CreateFHIRSurveyRequest();
	return proto.ondewo.survey.CreateFHIRSurveyRequest.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ondewo.survey.CreateFHIRSurveyRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ondewo.survey.CreateFHIRSurveyRequest}
 */
proto.ondewo.survey.CreateFHIRSurveyRequest.deserializeBinaryFromReader = function (msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 1:
				var value = new google_protobuf_struct_pb.Struct();
				reader.readMessage(value, google_protobuf_struct_pb.Struct.deserializeBinaryFromReader);
				msg.setFhirQuestionnaire(value);
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ondewo.survey.CreateFHIRSurveyRequest.prototype.serializeBinary = function () {
	var writer = new jspb.BinaryWriter();
	proto.ondewo.survey.CreateFHIRSurveyRequest.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ondewo.survey.CreateFHIRSurveyRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ondewo.survey.CreateFHIRSurveyRequest.serializeBinaryToWriter = function (message, writer) {
	var f = undefined;
	f = message.getFhirQuestionnaire();
	if (f != null) {
		writer.writeMessage(1, f, google_protobuf_struct_pb.Struct.serializeBinaryToWriter);
	}
};

/**
 * optional google.protobuf.Struct fhir_questionnaire = 1;
 * @return {?proto.google.protobuf.Struct}
 */
proto.ondewo.survey.CreateFHIRSurveyRequest.prototype.getFhirQuestionnaire = function () {
	return /** @type{?proto.google.protobuf.Struct} */ (
		jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Struct, 1)
	);
};

/**
 * @param {?proto.google.protobuf.Struct|undefined} value
 * @return {!proto.ondewo.survey.CreateFHIRSurveyRequest} returns this
 */
proto.ondewo.survey.CreateFHIRSurveyRequest.prototype.setFhirQuestionnaire = function (value) {
	return jspb.Message.setWrapperField(this, 1, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.ondewo.survey.CreateFHIRSurveyRequest} returns this
 */
proto.ondewo.survey.CreateFHIRSurveyRequest.prototype.clearFhirQuestionnaire = function () {
	return this.setFhirQuestionnaire(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ondewo.survey.CreateFHIRSurveyRequest.prototype.hasFhirQuestionnaire = function () {
	return jspb.Message.getField(this, 1) != null;
};

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ondewo.survey.SurveyFHIRAnswersResponse.repeatedFields_ = [2];

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
	 * Creates an object representation of this proto.
	 * Field names that are reserved in JavaScript and will be renamed to pb_name.
	 * Optional fields that are not set will be set to undefined.
	 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
	 * For the list of reserved names please see:
	 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
	 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
	 *     JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @return {!Object}
	 */
	proto.ondewo.survey.SurveyFHIRAnswersResponse.prototype.toObject = function (opt_includeInstance) {
		return proto.ondewo.survey.SurveyFHIRAnswersResponse.toObject(opt_includeInstance, this);
	};

	/**
	 * Static version of the {@see toObject} method.
	 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
	 *     the JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @param {!proto.ondewo.survey.SurveyFHIRAnswersResponse} msg The msg instance to transform.
	 * @return {!Object}
	 * @suppress {unusedLocalVariables} f is only used for nested messages
	 */
	proto.ondewo.survey.SurveyFHIRAnswersResponse.toObject = function (includeInstance, msg) {
		var f,
			obj = {
				surveyId: jspb.Message.getFieldWithDefault(msg, 1, ''),
				fhirQuestionnaireResponsesList: jspb.Message.toObjectList(
					msg.getFhirQuestionnaireResponsesList(),
					google_protobuf_struct_pb.Struct.toObject,
					includeInstance
				)
			};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ondewo.survey.SurveyFHIRAnswersResponse}
 */
proto.ondewo.survey.SurveyFHIRAnswersResponse.deserializeBinary = function (bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.ondewo.survey.SurveyFHIRAnswersResponse();
	return proto.ondewo.survey.SurveyFHIRAnswersResponse.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ondewo.survey.SurveyFHIRAnswersResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ondewo.survey.SurveyFHIRAnswersResponse}
 */
proto.ondewo.survey.SurveyFHIRAnswersResponse.deserializeBinaryFromReader = function (msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 1:
				var value = /** @type {string} */ (reader.readString());
				msg.setSurveyId(value);
				break;
			case 2:
				var value = new google_protobuf_struct_pb.Struct();
				reader.readMessage(value, google_protobuf_struct_pb.Struct.deserializeBinaryFromReader);
				msg.addFhirQuestionnaireResponses(value);
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ondewo.survey.SurveyFHIRAnswersResponse.prototype.serializeBinary = function () {
	var writer = new jspb.BinaryWriter();
	proto.ondewo.survey.SurveyFHIRAnswersResponse.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ondewo.survey.SurveyFHIRAnswersResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ondewo.survey.SurveyFHIRAnswersResponse.serializeBinaryToWriter = function (message, writer) {
	var f = undefined;
	f = message.getSurveyId();
	if (f.length > 0) {
		writer.writeString(1, f);
	}
	f = message.getFhirQuestionnaireResponsesList();
	if (f.length > 0) {
		writer.writeRepeatedMessage(2, f, google_protobuf_struct_pb.Struct.serializeBinaryToWriter);
	}
};

/**
 * optional string survey_id = 1;
 * @return {string}
 */
proto.ondewo.survey.SurveyFHIRAnswersResponse.prototype.getSurveyId = function () {
	return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * @param {string} value
 * @return {!proto.ondewo.survey.SurveyFHIRAnswersResponse} returns this
 */
proto.ondewo.survey.SurveyFHIRAnswersResponse.prototype.setSurveyId = function (value) {
	return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * repeated google.protobuf.Struct fhir_questionnaire_responses = 2;
 * @return {!Array<!proto.google.protobuf.Struct>}
 */
proto.ondewo.survey.SurveyFHIRAnswersResponse.prototype.getFhirQuestionnaireResponsesList = function () {
	return /** @type{!Array<!proto.google.protobuf.Struct>} */ (
		jspb.Message.getRepeatedWrapperField(this, google_protobuf_struct_pb.Struct, 2)
	);
};

/**
 * @param {!Array<!proto.google.protobuf.Struct>} value
 * @return {!proto.ondewo.survey.SurveyFHIRAnswersResponse} returns this
 */
proto.ondewo.survey.SurveyFHIRAnswersResponse.prototype.setFhirQuestionnaireResponsesList = function (value) {
	return jspb.Message.setRepeatedWrapperField(this, 2, value);
};

/**
 * @param {!proto.google.protobuf.Struct=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.protobuf.Struct}
 */
proto.ondewo.survey.SurveyFHIRAnswersResponse.prototype.addFhirQuestionnaireResponses = function (
	opt_value,
	opt_index
) {
	return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.google.protobuf.Struct, opt_index);
};

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ondewo.survey.SurveyFHIRAnswersResponse} returns this
 */
proto.ondewo.survey.SurveyFHIRAnswersResponse.prototype.clearFhirQuestionnaireResponsesList = function () {
	return this.setFhirQuestionnaireResponsesList([]);
};

goog.object.extend(exports, proto.ondewo.survey);
